# Dockerfile.airflow
FROM apache/airflow:2.9.2

# Switch to root to install packages
USER root
# 1. Force IPv4 + HTTPS
RUN echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4

# 2. Completely replace sources.list (REMOVE bullseye)
RUN rm -f /etc/apt/sources.list && \
    printf "deb https://deb.debian.org/debian bookworm main\n\
deb https://deb.debian.org/debian bookworm-updates main\n\
deb https://deb.debian.org/debian-security bookworm-security main\n" \
    > /etc/apt/sources.list

# 3. Update and install Java
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        openjdk-17-jdk \
        ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Install Java
#RUN apt-get update && apt-get install -y openjdk-17-jdk && rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Switch back to airflow user
USER airflow
